<?php

session_start();
$q=$_GET["q"];

//store USER id into a session variable
$_SESSION['user']=$q;

//get connection string variable from session
$db_UN=$_SESSION['un'];
$db_PASS=$_SESSION['pass'];
$db_DB=$_SESSION['db'];
$db_conn = ocilogon($db_UN, $db_PASS, $db_DB);

//get user information from database
//$str = "select * from client WHERE c_id = '".$q."'";
$str ="SELECT CLIENT.*, ACCESS_RIGHT.ACC_RIGHT_DESC as RIGHT FROM CLIENT INNER JOIN ACCESS_RIGHT ON CLIENT.ACC_RIGHT_ID = ACCESS_RIGHT.ACC_RIGHT_ID WHERE CLIENT.c_id = '".$q."'";
$parsed = ociparse($db_conn, $str);
ociexecute($parsed);
$numrows = ocifetchstatement($parsed, $results);

$Title= $results["TITLE"][0];
$Lname= $results["LNAME"][0];
$Fname= $results["FNAME"][0];
$Mname= $results["MNAME"][0];
$Address1=$results["ADD_1"][0];
$Address2=$results["ADD_2"][0];
$City=$results["CITY"][0];
$State=$results["STATE"][0];
$Zip=$results["ZIP"][0];
$Country=$results["COUNTRY"][0];
$Phone=$results["PHONE"][0];
$Email=$results["EMAIL"][0];
$Ind=$results["IND"][0];
$Profession=$results["PROF"][0];

echo "<table cellpadding='2' cellspacing='2' width='95%' align='center' style='font-family:Verdana; font-size:small'>";
echo	"<tr>";
echo        "<td align='right' width='50%'>&nbsp;<br />";
echo        	"Title:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>&nbsp;<br />";
echo        	"<b>" . strtoupper($results["TITLE"][0]) . "</b>";                                                                                                                             echo        "</td>";
echo    "</tr>";
echo    "<tr>";
echo        "<td align='right' width='50%'>";
echo            "Last Name:&nbsp;&nbsp;";
echo    	"</td>";
echo    	"<td align='left' width='50%'>";
echo            "<b>" . strtoupper($results["LNAME"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo    "<tr>";
echo    	"<td align='right' width='50%'>";
echo           "First Name:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["FNAME"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "MI:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["MNAME"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "User ID:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b><div id='got_userid'>" .strtoupper($results["USER_ID"][0]) . "</div></b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Adress:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" . strtoupper($results["ADD_1"][0]) ."</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Adress2:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["ADD_2"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "City:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["CITY"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "State:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["STATE"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Zip:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["ZIP"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Country:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["COUNTRY"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Phone:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["PHONE"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "E-Mail:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b><div id='got_email'>" .strtoupper($results["EMAIL"][0]) . "</div></b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Agency/Company:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["IND"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Profession:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["PROF"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Access Right:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper($results["RIGHT"][0]) . "</b>";
echo        "</td>";
echo    "</tr>";
echo	"<tr>";
echo    	"<td align='right' width='50%'>";
echo           "Delete Flag:&nbsp;&nbsp;";
echo        "</td>";
echo        "<td align='left' width='50%'>";
echo            "<b>" .strtoupper(($results["DEL_FLAG"][0] == "1"? "0 - inactive user" : "1 - active user")) . "</b>";
echo        "</td>";
echo    "</tr>";
?>
</TABLE>
                                                                        
<?php
oci_close($db_conn);
?>

